In [47]:
from numpy import *
import pandas as pd
import matplotlib.pyplot as plt
import operator


In [67]:
#  def __init__(self,x_var_to_classify,dataSet,labels,no_of_neighbors):
#      self.x_var_to_classify=x_var_to_classify
#      self.dataSet=dataSet
#      self.labels=labels
#      self.no_of_neighbors=no_of_neighbors
#      
def KNN_Classification(x_var_to_classify,dataSet,labels,no_of_neighbors):
    dataSetSize=dataSet.shape[0]
    diffMat=tile(x_var_to_classify,(dataSetSize,1))-dataSet
    sqDiffMat=diffMat**2
    sqDistances=sqDiffMat.sum(axis=1)
    distances=sqDistances**0.5
    sortedDistanceIndices=distances.argsort()
    classCount={}
    for i in range(no_of_neighbors):
        voteIlabel = labels[sortedDistanceIndices[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

In [49]:
from sklearn.datasets import load_iris

In [50]:
iris=load_iris()

In [51]:
type(iris)

sklearn.datasets.base.Bunch

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [9]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
iris.data.shape
i=0

In [77]:
from sklearn import model_selection
x_train,x_test,y_train,y_test=model_selection.train_test_split(iris.data,iris.target,test_size=0.3)

In [79]:
result=[]
for i in range(0,len(x_test)):
    result.append(KNN_Classification(x_test[i],x_train,y_train,5))

In [72]:
y_test

array([1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 0, 0, 0, 1, 1,
       1, 1, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 2, 1, 0, 2, 0, 2, 2, 1, 2, 2])

In [74]:
result

array([1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 1, 1, 2, 0, 0, 0, 0, 1, 1,
       2, 1, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 2, 2, 0, 2, 0, 2, 2, 1, 2, 2])

In [75]:
from sklearn.metrics import accuracy_score

In [80]:
accuracy_score(y_test, result)

0.9555555555555556